main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('tickets/', views.tickets_index, name='index'),
    path('tickets/<int:ticket_id>/', views.tickets_detail, name='detail'),
    path('tickets/create/', views.TicketCreate.as_view(), name='tickets_create'),
    path('accounts/signup/', views.signup, name='signup'),
    path('tickets/<int:pk>/update/', views.TicketUpdate.as_view(), name='tickets_update'),
    path('tickets/<int:pk>/delete/', views.TicketDelete.as_view(), name='tickets_delete'),
    path('tickets/<int:ticket_id>/add_highlight/', views.add_highlight, name='add_highlight'),
    path('tickets/<int:ticket_id>/add_artist/', views.add_artist, name='add_artist'),
    path('tickets/<int:ticket_id>/assoc_artist/<int:artist_id>/', views.assoc_artist, name='assoc_artist'),
    path('tickets/<int:ticket_id>/unassoc_artist/<int:artist_id>/', views.unassoc_artist, name='unassoc_artist'),
    path('locations/', views.LocationIndex.as_view(), name="locations_index"),
    path('locations/<int:pk>/', views.LocationDetail.as_view(), name='location_detail'),
    path('locations/create/', views.LocationCreate.as_view(), name='locations_create'), 
    path('tickets/<int:ticket_id>/add_sportevent', views.add_sportevent, name='add_sportevent')
    ]

stubsaver/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


EVENT_TYPES = (
    ('C', 'Concert'),
    ('S', 'Sport'),
)

# Create your models here.


class Artist(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
    class Meta: 
        ordering = ['name']


class Location(models.Model):
    name = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    maps_url = models.URLField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('location_detail', kwargs={'pk': self.id})
    
    class Meta: 
        ordering = ['name']


class Ticket(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateField('date (yyyy-mm-dd)')
    companion = models.CharField(max_length=250)
    event_type = models.CharField(max_length=1, choices=EVENT_TYPES, default=EVENT_TYPES[0][0])
    artists = models.ManyToManyField(Artist, blank=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} on {self.date}"

    def get_absolute_url(self):
        return reverse('detail', kwargs={'ticket_id': self.id})
    
    class Meta: 
        ordering = ['-date']


class SportEvent(models.Model):
    sport = models.CharField(max_length=100)
    league = models.CharField('League/ Competition', max_length=100)
    home_team = models.CharField(max_length=100)
    away_team = models.CharField(max_length=100)
    home_score = models.IntegerField()
    away_score = models.IntegerField()
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.home_team} v. {self.away_team}"


class Highlight(models.Model):
    content = models.TextField('Your Highlights')
    video_url = models.URLField(null=True, blank=True)
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

main_app/forms.py
from django.forms import ModelForm
from .models import Highlight, Artist, SportEvent

class HighlightForm(ModelForm):
    class Meta:
        model = Highlight
        fields = ['content', 'video_url']

class ArtistForm(ModelForm):
    class Meta:
        model = Artist
        fields = ['name']

class SportEventForm(ModelForm):
    class Meta:
        model = SportEvent
        fields = ['sport', 'league', 'home_team', 'away_team', 'home_score', 'away_score']

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Ticket, Artist, Location
from .forms import HighlightForm, ArtistForm, SportEventForm

# Create your views here.
def home(request):
    return render(request, 'home.html')

@login_required
def tickets_index(request):
    tickets = Ticket.objects.filter(user=request.user)
    return render(request, 'tickets/index.html', {
        'tickets': tickets
    })

@login_required
def tickets_detail(request, ticket_id):
    tickets = Ticket.objects.filter(user=request.user)
    ticket = tickets.get(id=ticket_id)
    id_list = ticket.artists.all().values_list('id')
    unassociated_artists = Artist.objects.exclude(id__in=id_list)
    highlight_form = HighlightForm()
    artist_form = ArtistForm()
    sportevent_form = SportEventForm()
    return render(request, 'tickets/detail.html', {
        'ticket': ticket,
        'highlight_form': highlight_form,
        'artists': unassociated_artists, 
        'artist_form': artist_form,
        'sportevent_form': sportevent_form
    })

@login_required
def add_highlight(request, ticket_id):
    form = HighlightForm(request.POST)
    if form.is_valid():
        new_highlight = form.save(commit=False)
        new_highlight.ticket_id = ticket_id
        new_highlight.save()
    return redirect('detail', ticket_id=ticket_id)

@login_required
def add_artist(request, ticket_id):
    form = ArtistForm(request.POST)
    if form.is_valid():
        new_artist = form.save()
        new_artist.save()
    return redirect('detail', ticket_id=ticket_id)

@login_required
def add_sportevent(request, ticket_id):
    form = SportEventForm(request.POST)
    if form.is_valid():
        new_sportevent = form.save(commit=False)
        new_sportevent.ticket_id = ticket_id
        new_sportevent.user = request.user
        new_sportevent.save()
    return redirect('detail', ticket_id=ticket_id)

@login_required
def assoc_artist(request, ticket_id, artist_id):
    Ticket.objects.get(id=ticket_id).artists.add(artist_id)
    return redirect('detail', ticket_id=ticket_id)

@login_required
def unassoc_artist(request, ticket_id, artist_id):
    Ticket.objects.get(id=ticket_id).artists.remove(artist_id)
    return redirect('detail', ticket_id=ticket_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

class TicketCreate(LoginRequiredMixin, CreateView):
    model = Ticket
    fields = ['name', 'date', 'location', 'companion', 'event_type']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class TicketUpdate(LoginRequiredMixin, UpdateView):
    model = Ticket
    fields = ['name', 'date', 'location', 'companion', 'event_type']

class TicketDelete(LoginRequiredMixin, DeleteView):
    model = Ticket
    success_url = '/tickets'

class LocationIndex(LoginRequiredMixin, ListView):
    model = Location

    # https://stackoverflow.com/questions/24725617/how-to-make-generic-listview-only-show-users-listing
    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

class LocationDetail(LoginRequiredMixin, DetailView):
    model = Location

class LocationCreate(LoginRequiredMixin, CreateView):
    model = Location
    fields = ['name', 'city', 'country', 'maps_url']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>StubSaver</title>
</head>

<body>
    <header class="hero is-small is-dark mb-4">
        <div class="hero-body">
            <h1 class="title is-1">StubSaver</h1>
            <p class="subtitle is-5">
                <a href="{% url 'home' %}">Home</a> |
                {% if user.is_authenticated %}
                <a href="{% url 'index' %}">All Tickets</a> | 
                <a href="{% url 'tickets_create' %}">Add Ticket</a> |
                <a href="{% url 'locations_index'%}">All Locations</a> |
                <a href="{% url 'locations_create' %}">Add Location</a> |
                <a href="{% url 'logout' %}">Log Out</a>
                {% else %}
                <a href="{% url 'signup' %}">Sign Up</a> | 
                <a href="{% url 'login' %}">Log In</a>
                {% endif %}
            </p>
        </div>
    </header>
    <div class="container mx-5">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="card has-background-light">
    <div class="card-content">
        <div class="media">
            <div class="media-content">
                <p class="title is-3">🎟️ Welcome 🎟️</p>
            </div>
        </div>

        <div class="content">
            <p>First, log in/sign up. There is no functionality of our website without first being logged in.
            </p>
        
            <p>Once logged in, you will be redirected to your ticket list. </p>
        
            <p>First time using the website? This page will be empty. Select "Add Ticket" from the Nav bar to be directed to the page to create a ticket.</p>
        
            <p>Follow the form to generate your ticket. Date is in the format of YYYY-MM-DD. Once done, click "Submit"</p>
        
            <p>Once submitted, you will be taken to the ticket details page, showing you the details you just entered.</p>
        
            <p>Repeat this for as many tickets as you'd like, and return to "All Tickets" to view the basic information.</p>
        
            <p>Finished? Feel free to log out.</p>
        </div>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/location_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="column is-one-third">
    <div class="card has-background-light">
        <div class="card-content">
            <h1 class="title is-3">{{object.name}}</h1>
            <p>City: {{object.city}}</p>
            <p>Country: {{object.country}}</p>
            {% if object.maps_url %}
            <p><a href="{{object.maps_url}}">Maps URL</a></p>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

main_app/templates/main_app/location_form.html
{% extends 'base.html' %}

{% block content %}
<div class="card has-background-light">
  <div class="card-content">
    {% if object %}
    <h1 class="title is-3">Edit {{object.name}}</h1>
    {% else %}
    <h1 class="title is-3">Add a Location</h1>
    {% endif %}
    <form action="" method="POST">
      {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>
      <button type="submit" class="button is-info mt-3">Submit</button>
    </form>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/location_list.html
{% extends 'base.html' %}

{% block content %}

<h1 class="title has-text-white-ter">All Locations</h1>
<div class="columns is-multiline" style="padding: 2rem">
    {% for object in object_list %}

    <div class="column is-one-quarter">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4"><a href="{% url 'location_detail' object.id %}">{{ object.name }}</a></p>
                        <p class="subtitle is-6">{{ object.city }}</p>
                    </div>
                </div>

                <div class="content">
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

main_app/templates/main_app/ticket_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="card has-background-light">
  <div class="card-content">
    <h1 class="title is-3">Delete Ticket</h1>

    <h4 class="subtitle is-5">Are you sure you want to delete {{ object.name }}?</h4>

    <form action="" method="POST">
      {% csrf_token %}
      <button type="submit" class="button is-danger">Delete</button>
      <a href="{% url 'detail' ticket.id %}" class="button is-info">Cancel</a>
    </form>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/ticket_form.html
{% extends 'base.html' %}

{% block content %}
<div class="card has-background-light">
  <div class="card-content">
    {% if object %}
    <h1 class="title is-3">Edit {{object.name}}</h1>
    {% else %}
    <h1 class="title is-3">Add a Ticket</h1>
    {% endif %}
    <form action="" method="POST">
      {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>
      <button type="submit" class="button is-info mt-3">Submit</button>
    </form>
  </div>
</div>
{% endblock %}

main_app/templates/tickets/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="columns">
    <div class="column has-background-light">
        <div class="card has-background-info-light">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        {% if ticket.event_type == 'C' %}
                        <p class="title is-3">{{ ticket.name }} 🎵</p>
                        {% else %}
                        <p class="title is-3">{{ ticket.name }}</p>
                        {% endif %}
                        <p class="subtitle is-5">{{ ticket.date }}</p>
                    </div>
                </div>

                <div class="content">
                    <p>Went with: {{ ticket.companion }}</p>
                    {% if ticket.location == null %}
                    <p>Location: Not Specified</p>
                    {% else %}
                    <p>Location: <a href="/locations/{{ ticket.location.id }}">{{ ticket.location }}</a> </p>
                    {% endif %}
                    <p>
                        <a href="{% url 'tickets_update' ticket.id %}">Edit</a> |
                        <a href="{% url 'tickets_delete' ticket.id %}">Delete</a>
                    </p>
                </div>
            </div>
        </div>
        {% if ticket.event_type == 'C' %}
        <div class="columns mt-5">
            <div class="column">
                <h3 class="title is-5 mb-2">All the Concert's Performers:</h3>
                {% if ticket.artists.count %}
                <table class="table is-hoverable is-fullwidth">
                    <thead>
                        <tr>
                            <th>Artist</th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for artist in ticket.artists.all %}
                        <tr>
                            <td>{{ artist.name }}</td>
                            <td>
                                <form action="{% url 'unassoc_artist' ticket.id artist.id %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="button is-danger is-small">Remove</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <h5>No Artist added</h5>
                {% endif %}
            </div>
            <div class="column"></div>
        </div>
        <div class="columns">
            <div class="column">
                <h3 class="title is-5 mb-2">Your Artists</h3>
                {% if artists.count %}
                <table class="table is-hoverable is-fullwidth">
                    <thead>
                        <tr>
                            <th>Artist</th>
                            <th> </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for artist in artists.all %}
                        <tr>
                            <td>{{ artist.name }}</td>
                            <td>
                                <form action="{% url 'assoc_artist' ticket.id artist.id %}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="button is-success is-small">Add</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <h5>{{ticket.name}} has all the available artists.</h5>
                {% endif %}
            </div>
            <div class="column">
                <h3 class="title is-5 mb-2">Add An Artist</h3>
                <form action="{% url 'add_artist' ticket.id %}" method="POST">
                    {% csrf_token %}
                    {{ artist_form.as_p }}
                    <button type="submit" class="button is-info is-small mt-2">Add Artist</button>
                </form>
            </div>
        </div>
        {% endif %}

        {% if ticket.event_type == 'S' %}
        {% if ticket.sportevent_set.all.count > 0 %}
        <h3 class="title is-4 mt-3 mb-2">Game Details</h3>
        <table class="table is-hoverable">
            <tbody>
                {% for event in ticket.sportevent_set.all %}
                <tr>
                    <th>Sport</th>
                    <td>{{ event.sport }}</td>
                </tr>
                <tr>
                    <th>League/ Competition</th>
                    <td>{{ event.league }}</td>
                </tr>
                <tr>
                    <th>Home Team</th>
                    <td>{{ event.home_team }}</td>
                </tr>
                <tr>
                    <th>Away Team</th>
                    <td>{{ event.away_team }}</td>
                </tr>
                <tr>
                    <th>Final Score</th>
                    <td>{{ event.home_score }} - {{ event.away_score }}</td>
                </tr>
                <tr>
                    <th>Winner</th>
                    {% if event.home_score > event.away_score %}
                    <td>{{event.home_team}}</td>
                    {% elif event.away_score > event.home_score %}
                    <td>{{event.away_team}}</td>
                    {% else %}
                    <td>Draw</td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h3 class="title is-5 mt-3 mb-1">Add Game Details</h3>
        <form action="{% url 'add_sportevent' ticket.id %}" method="POST">
            {% csrf_token %}
            {{ sportevent_form.as_p }}
            <button type="submit" class="button is-info is-small mt-2 mb-3">Add Game Details</button>
        </form>
        {% endif %}
        {% endif %}
    </div>

    <div class="column has-background-light">
        <form action="{% url 'add_highlight' ticket.id %}" method="POST">
            {% csrf_token %}
            {{ highlight_form.as_p }}
            <button type="submit" class="button is-info is-small mt-2 mb-3">Add Highlight</button>
        </form>
        {% if ticket.highlight_set.all.count > 0 %}
        <table class="table is-fullwidth mt-3">
            <thead>
                <tr>
                    <th>Highlights</th>
                    <th> </th>
                </tr>
            </thead>
            <tbody>
                {% for highlight in ticket.highlight_set.all %}
                <tr>
                    <td>{{highlight.content}}</td>
                    {% if highlight.video_url == null %}
                    <td></td>
                    {% else %}
                    <td><a href="{{highlight.video_url}}">Video Link</a></td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
{% endblock %}

main_app/templates/tickets/index.html
{% extends 'base.html' %}
{% block content %}

<h1 class="title has-text-white-ter">Ticket List</h1>

<div class="columns is-multiline" style="padding: 2rem">
    {% for ticket in tickets %}

    <div class="column is-one-quarter">
        <div class="card">
            <div class="card-image">
                <figure class="image is-2by1">
                    {% if ticket.event_type == 'C' %}
                    <img src="https://i.imgur.com/YgvDQZR.png" alt="Placeholder image">
                    {% else %}
                    <img src="https://i.imgur.com/0zuympu.png" alt="Placeholder image">
                    {% endif %}
                </figure>
            </div>
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4"><a href="{% url 'detail' ticket.id %}">{{ ticket.name }}</a></p>
                        <p class="subtitle is-6">{{ ticket.date}}</p>
                    </div>
                </div>

                <div class="content">
                    {% if ticket.location != null %}
                    {{ ticket.location }}
                    {% else %}
                    <p>No location added</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}